#pragma once
#include <unordered_map>
#include <string>

// Generated by EmbedResGenerator
namespace TestRes
{
    extern const char fr0xffe1297f5a13080_bGV2ZWwuZGF0[];
    extern const std::unordered_map<std::string, std::pair<const char*, size_t>> resourceMap;
} // namespace TestRes
