#pragma once
#include <unordered_map>
#include <string>

// Generated by EmbedResGenerator
namespace INCLUDE_MOD_RES
{
    extern const unsigned char f0x30d0bee5af19a576_bWFuaWZlc3QuanNvbg[];
    extern const unsigned char fr0x8dc3d815a132de8_REVCVUdfRU5WX1NDUklQVC9tb2RNYWluLnB5[];
    extern const unsigned char fr0x3b3acb964cb54134_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSU4ucHk[];
    extern const unsigned char fr0x35997f864c7c02c9_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSW5mb3JtYXRpb24ucHk[];
    extern const unsigned char fr0x4c364a540f9bd425_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvUXVNb2QucHk[];
    extern const unsigned char fr0xe898a59abc45e9b_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvVXRpbC5weQ[];
    extern const unsigned char fr0x28d814340cd25098_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvQ2xpZW50LnB5[];
    extern const unsigned char f0xce0b1c72ba7945d_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2VydmVyLnB5[];
    extern const unsigned char f0x4fa2a6c36b8d46ca_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2hhcmVkUmVzLnB5[];
    extern const std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> resourceMap;
} // namespace INCLUDE_MOD_RES
