#pragma once
#include <unordered_map>
#include <string>

// Generated by EmbedResGenerator
namespace INCLUDE_MOD_RES
{
    extern const unsigned char fr0x7ef7cf4a511c2c8b_bWFuaWZlc3QuanNvbg[];
    extern const unsigned char fr0x3bc60982c7fe94c2_REVCVUdfRU5WX1NDUklQVC9tb2RNYWluLnB5[];
    extern const unsigned char fr0x18440425b0bf12e5_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSU4ucHk[];
    extern const unsigned char f0x210153022d61cacc_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSW5mb3JtYXRpb24ucHk[];
    extern const unsigned char f0x1865ad242d4bb838_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvUXVNb2QucHk[];
    extern const unsigned char fr0x30c2149b616450f1_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvVXRpbC5weQ[];
    extern const unsigned char f0x6601fcc42b247ec7_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvQ2xpZW50LnB5[];
    extern const unsigned char f0x39312d6354fb5187_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2VydmVyLnB5[];
    extern const unsigned char f0x4ad62c22e66315cf_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2hhcmVkUmVzLnB5[];
    extern const std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> resourceMap;
} // namespace INCLUDE_MOD_RES
