#pragma once
#include <unordered_map>
#include <string>

// Generated by EmbedResGenerator
namespace INCLUDE_MOD_RES
{
    extern const unsigned char fr0x5d4b04062c67f499_bWFuaWZlc3QuanNvbg[];
    extern const unsigned char fr0x2c7849e7aebe3ac8_REVCVUdfRU5WX1NDUklQVC9Db25maWcucHk[];
    extern const unsigned char f0x3b0a8eb50060c0ca_REVCVUdfRU5WX1NDUklQVC9HYW1lLnB5[];
    extern const unsigned char f0x21f601b8be49c82a_REVCVUdfRU5WX1NDUklQVC9JUENTeXN0ZW0ucHk[];
    extern const unsigned char f0x64505a44db2e1ad3_REVCVUdfRU5WX1NDUklQVC9tb2RNYWluLnB5[];
    extern const unsigned char fr0x76ee2292373b3e5_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSU4ucHk[];
    extern const unsigned char f0x69cf26ac58fff141_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSW5mb3JtYXRpb24ucHk[];
    extern const unsigned char f0xdbc9a081739c498_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvUXVNb2QucHk[];
    extern const unsigned char f0x724040d7b2eb1399_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvVXRpbC5weQ[];
    extern const unsigned char f0x4754245d74c28773_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvQ2xpZW50LnB5[];
    extern const unsigned char f0x20f3eda39ee28718_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2VydmVyLnB5[];
    extern const unsigned char f0x6cd5002851c11f76_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2hhcmVkUmVzLnB5[];
    extern const std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> resourceMap;
} // namespace INCLUDE_MOD_RES
