#pragma once
#include <unordered_map>
#include <string>

// Generated by EmbedResGenerator
namespace INCLUDE_MOD_RES
{
    extern const unsigned char f0x39fb478f273cfe76_bWFuaWZlc3QuanNvbg[];
    extern const unsigned char f0x4d9b58512e53c3a3_REVCVUdfRU5WX1NDUklQVC9Db25maWcucHk[];
    extern const unsigned char f0x7f605f336c47f6b8_REVCVUdfRU5WX1NDUklQVC9HYW1lLnB5[];
    extern const unsigned char fr0x695565e093fedded_REVCVUdfRU5WX1NDUklQVC9JUENTeXN0ZW0ucHk[];
    extern const unsigned char f0x72926e93340ff1b1_REVCVUdfRU5WX1NDUklQVC9tb2RNYWluLnB5[];
    extern const unsigned char fr0x2037761d0de916da_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSU4ucHk[];
    extern const unsigned char f0x4ae039c451f11864_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvSW5mb3JtYXRpb24ucHk[];
    extern const unsigned char f0x37a198aa3eed2785_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvUXVNb2QucHk[];
    extern const unsigned char f0x7f78556c31bfe393_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvVXRpbC5weQ[];
    extern const unsigned char f0x1e3cebdc5d2de875_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvQ2xpZW50LnB5[];
    extern const unsigned char fr0x4eed4f2f30e1b8ae_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2VydmVyLnB5[];
    extern const unsigned char fr0x7ca100252a7b5be2_REVCVUdfRU5WX1NDUklQVC9RdU1vZExpYnMvU3lzdGVtcy9Mb2FkZXIvU2hhcmVkUmVzLnB5[];
    extern const std::unordered_map<std::string, std::pair<const unsigned char*, size_t>> resourceMap;
} // namespace INCLUDE_MOD_RES
